### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CleverSource** [llapresi/taut-api-prototype#1]
So I want to make a pull request but when I even run from source code it just breaks, gives me tons of console errors saying it requires http, so I put it on my site and same thing happens and my site is http and https

**Comment by llapresi** [comment]
You're running "npm install" after cloning the repo to install all the dependencies before you run with "npm start" right? "http" is a built-in node module so it seems pretty weird it's giving that as a result.

**Comment by CleverSource** [comment]
I've been running off of the index.html, instead of localhost:3000, my bad. :P

**Comment by CleverSource** [comment]
Also I notice you seem to be using that Who Messager stuff since I saw by the favicon, I'd highly advise agains't it, unless it is just the favicon and you stole there CSS.

**Comment by CleverSource** [comment]
I fixed the issue, also I highly recommend turning this into an electron app it will work better down the road if you plan to add video chat, voice chat, etc, also if this is really going to be a slack/discord clone i'd love to see how you go with making sign up's and espically making the API! :)

Would love to see some discord alternatives.

**Comment by CleverSource** [comment]
Also to add on to that, It would be interesting to see a system like discord's with the discriminator's like CleverSource#9923, etc, allows for making it so people can't get added randomly. I don't see you planing to copy discord all the way to its core but making stuff like badges like Discord Dev etc would be interesting.

**Comment by CleverSource** [comment]
I hope to see you turn this into something and maybe grow a community rather than just making this as a student project.

**Comment by llapresi** [comment]
Replying to a comment that I got sent via in this thread but I honestly don't know what "Who Messenger" is, I wrote the CASE stuff by hand

**Comment by llapresi** [comment]
I will say that yeah, I might continue working on this thing as a project. I dunno, who knows
